"""PASS-223: offline simulation of periodic/local re-anchoring against the
Pass 222 full-song candidate trace, without touching production code or
re-running the pipeline.

Approach (an approximation, explicitly not a substitute for real
verification -- see caveats below): replay the 101 captured ticks in order,
maintaining our own `committed_so_far` sequence. At each tick where the
real run's arbitration was triggered (a genuine close-candidate conflict),
recompute two scores for every candidate that was in that conflict:
  1. phase_consistency_score against OUR committed_so_far (not the frozen
     original run's committed_before -- this lets a changed earlier
     decision propagate forward).
  2. absolute_grid_score against a LOCAL anchor: the most recent bar in
     committed_so_far that is a multiple of `reanchor_interval` bars back
     (re-anchored periodically, unlike Pass 221's single whole-song anchor).
Combined score = 50/50 average of the two (same combiner Pass 221 used).
Ticks with no triggered conflict just keep the original single winner.

Caveats (why this is a screening tool, not proof): the candidate SET at
each tick was generated by the real pipeline using the real committed
history, so if our simulated history diverges, the exact onsets offered at
a given tick may not perfectly match what a real re-run would have found
(the search window's position depends on committed_before). This is a
reasonable approximation for evaluating an ARBITRATION RULE change (which
candidate wins) since it doesn't depend on discovering new onsets, but a
"looks good" result here still needs the full real-pipeline verification
protocol before it can be trusted.
"""

from __future__ import annotations

import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TRACE_PATH = os.path.join(ROOT, "scratch", "pass222_full_song_candidate_trace.jsonl")
GOLDEN_PATH = r"d:\Users\666\Music\2\【Hatsune_Miku】_World_is_Mine_ryo（supercell）【初音ミク】\reports\measure_map.json"

SEGMENTS = [
    ("Intro", 0.0, 25.813243),
    ("Verse 1", 25.813243, 86.907256),
    ("Chorus 1", 86.907256, 147.977778),
    ("Outro", 147.977778, float("inf")),
]


def _load_trace():
    with open(TRACE_PATH, encoding="utf-8") as f:
        return [json.loads(line) for line in f if line.strip()]


def _phase_consistency_score(candidate_time, committed, expected):
    residuals = []
    for previous in committed:
        delta = float(candidate_time) - float(previous)
        if delta <= 0:
            continue
        bars = max(1, round(delta / expected))
        residuals.append(abs(delta - bars * expected))
    if not residuals:
        return 0.0
    mean_residual = sum(residuals) / len(residuals)
    score = max(0.0, min(1.0, 1.0 - mean_residual / max(expected * 0.5, 1e-6)))
    # Production rounds to 6 decimals before comparing (module3_barstart_v2_bt.py
    # BarStartCandidateCommitNode._phase_consistency_score). Without this, two
    # candidates that are exactly tied in production differ in the 15th+
    # significant digit here due to float arithmetic order, and max()'s
    # tie-break on -time never gets a chance to fire.
    return round(score, 6)


def simulate(trace, reanchor_interval=None, weight_absolute=0.5):
    """reanchor_interval=None reproduces the ORIGINAL (unmodified) behavior
    (pure phase_consistency_score, no absolute grid at all) as a sanity
    baseline. A positive int enables the periodic-local-anchor absolute
    score, re-anchored every `reanchor_interval` committed bars."""
    # Seed with the real run's initial state (ManualCommittedBarStartsSeedNode
    # etc. run before the first BarStartCandidateCommitNode tick) -- without
    # this the simulator starts from nothing and diverges from tick 1.
    committed = [float(t) for t in (trace[0].get("committed_before") or [])]
    for tick in trace:
        decision = tick.get("decision", {})
        arb = decision.get("candidate_arbitration", {}) or {}
        expected = arb.get("expected_bar_duration_sec")
        real_committed_time = tick.get("committed_after_last")

        if not arb.get("triggered") or not expected or not committed:
            # No real conflict to re-arbitrate (or too early to have any
            # committed history yet) -- keep the original decision verbatim.
            if real_committed_time is not None:
                committed.append(float(real_committed_time))
            continue

        cand_list = arb.get("candidates", [])
        if not cand_list:
            if real_committed_time is not None:
                committed.append(float(real_committed_time))
            continue

        commit_threshold = arb.get("commit_threshold")

        scored = []
        for entry in cand_list:
            cand = entry.get("candidate", {})
            t = cand.get("time")
            conf = cand.get("confidence", 0.0)
            if t is None:
                continue
            phase_score = _phase_consistency_score(t, committed, expected)
            if reanchor_interval:
                anchor_idx = max(0, (len(committed) - 1) // reanchor_interval * reanchor_interval)
                local_anchor = [committed[anchor_idx]]
                absolute_score = _phase_consistency_score(t, local_anchor, expected)
                combined = (1 - weight_absolute) * phase_score + weight_absolute * absolute_score
            else:
                combined = phase_score
            # Pass 202's confidence-threshold gate: candidates that clear
            # commit_threshold must always outrank ones that don't,
            # regardless of phase/combined score. Omitting this (as an
            # earlier version of this simulator did) silently reintroduces
            # the exact bug Pass 202 fixed in production and makes the
            # "baseline" replay diverge sharply from real output.
            clears = conf >= commit_threshold if commit_threshold is not None else True
            scored.append((clears, combined, conf, -t, t))

        # max() with the same tie-break priority as production code.
        best = max(scored, key=lambda item: (item[0], item[1], item[2], item[3]))
        committed.append(best[4])

    return sorted(set(round(t, 6) for t in committed))


def real_raw_sequence(trace):
    """Reconstruct the REAL pipeline's raw BarStartCandidateCommitNode loop
    output (seed + every committed_after_last), i.e. the same basis our
    simulate() produces -- BEFORE any downstream gap-repair/interpolation
    node runs. This is what simulate(reanchor_interval=None) should be
    validated against, NOT golden directly: golden reflects the final
    post-repair grid, which has more bars (repair fills gaps) than the raw
    loop ever committed, so an index-aligned comparison against golden is
    only a fair comparison once density matches."""
    committed = [float(t) for t in (trace[0].get("committed_before") or [])]
    for tick in trace:
        t = tick.get("committed_after_last")
        if t is not None:
            committed.append(float(t))
    return sorted(set(round(t, 6) for t in committed))


def diff_sequences(sim, real, label):
    print(f"=== {label}: sim={len(sim)} real={len(real)} ===")
    n = min(len(sim), len(real))
    mismatches = [(i, sim[i], real[i]) for i in range(n) if abs(sim[i] - real[i]) > 1e-6]
    if not mismatches:
        print(f"  first {n} entries match exactly.")
    else:
        print(f"  first mismatch at index {mismatches[0][0]}: sim={mismatches[0][1]} real={mismatches[0][2]}")
        print(f"  total mismatches in overlap: {len(mismatches)}/{n}")
        for i, s, r in mismatches[:5]:
            print(f"    idx={i} sim={s} real={r} diff={s - r:.6f}")
    print()


def compare_to_golden(committed, golden_downbeats, label):
    print(f"=== {label}: total bars = {len(committed)} (golden = {len(golden_downbeats)}) ===")
    for name, start, end in SEGMENTS:
        seg = [b for b in committed if start <= b < end]
        g_seg = [g for g in golden_downbeats if start <= g < end]
        n = min(len(seg), len(g_seg))
        if n == 0:
            print(f"  {name:>10}: no overlap")
            continue
        residuals = [seg[i] - g_seg[i] for i in range(n)]
        mean_abs = sum(abs(r) for r in residuals) / n
        max_abs = max(abs(r) for r in residuals)
        print(f"  {name:>10}: v2={len(seg):>3} golden={len(g_seg):>3} mean_abs={mean_abs:.3f} max_abs={max_abs:.3f}")
    print()


def main():
    trace = _load_trace()
    with open(GOLDEN_PATH, encoding="utf-8") as f:
        golden = json.load(f)["measure_map"]
    golden_downbeats = [float(m["start_time"]) for m in golden]

    baseline = simulate(trace, reanchor_interval=None)
    real_raw = real_raw_sequence(trace)
    diff_sequences(baseline, real_raw, "VALIDATION: baseline vs real raw loop output")
    compare_to_golden(baseline, golden_downbeats, "baseline (original phase_consistency_score only)")

    for interval in (4, 6, 8, 12, 16, 24):
        result = simulate(trace, reanchor_interval=interval, weight_absolute=0.5)
        compare_to_golden(result, golden_downbeats, f"periodic re-anchor every {interval} bars (weight=0.5)")


if __name__ == "__main__":
    raise SystemExit(main())
